### ISSUE TITLE
固件问题？

### ISSUE THREAD

**Issue by HSK077** [vpei/openwrt-s905d-n1#1]
写入U盘后，插上N1启动获取不到IP地址

**Comment by vpei** [comment]
哪个固件？网线接外网，WIFI是内网。

**Comment by HSK077** [comment]
正常写进U盘，N1启动后一直未能成功获取IP地址
openwrt_n1_k5.4.156_2021.11.01.2247.img.gz

**Comment by HSK077** [comment]
我试下刚才最新编译的版本
反馈：试过也不能启动
U盘肯定没问题，写入别的固件一次成功
![Snipaste_2021-11-02_22-36-06](https://user-images.githubusercontent.com/54111827/139868550-ab289dcd-60ef-4138-992e-6617a7a67b49.png)

**Comment by vpei** [comment]
这个是我编的自己用，直接接外网的。你需要直接Fork过去，再把里面的配置文件删除，自己编译一下就行了。
